// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: curd/curd.proto

package curd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Curd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Curd) Reset() {
	*x = Curd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_curd_curd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Curd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Curd) ProtoMessage() {}

func (x *Curd) ProtoReflect() protoreflect.Message {
	mi := &file_curd_curd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Curd.ProtoReflect.Descriptor instead.
func (*Curd) Descriptor() ([]byte, []int) {
	return file_curd_curd_proto_rawDescGZIP(), []int{0}
}

func (x *Curd) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateCurdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Curd *Curd `protobuf:"bytes,1,opt,name=curd,proto3" json:"curd,omitempty"`
}

func (x *CreateCurdReq) Reset() {
	*x = CreateCurdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_curd_curd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCurdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCurdReq) ProtoMessage() {}

func (x *CreateCurdReq) ProtoReflect() protoreflect.Message {
	mi := &file_curd_curd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCurdReq.ProtoReflect.Descriptor instead.
func (*CreateCurdReq) Descriptor() ([]byte, []int) {
	return file_curd_curd_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCurdReq) GetCurd() *Curd {
	if x != nil {
		return x.Curd
	}
	return nil
}

type CreateCurdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Curd *Curd `protobuf:"bytes,1,opt,name=curd,proto3" json:"curd,omitempty"`
}

func (x *CreateCurdRes) Reset() {
	*x = CreateCurdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_curd_curd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCurdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCurdRes) ProtoMessage() {}

func (x *CreateCurdRes) ProtoReflect() protoreflect.Message {
	mi := &file_curd_curd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCurdRes.ProtoReflect.Descriptor instead.
func (*CreateCurdRes) Descriptor() ([]byte, []int) {
	return file_curd_curd_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCurdRes) GetCurd() *Curd {
	if x != nil {
		return x.Curd
	}
	return nil
}

type UpdateCurdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Curd *Curd `protobuf:"bytes,1,opt,name=curd,proto3" json:"curd,omitempty"`
}

func (x *UpdateCurdReq) Reset() {
	*x = UpdateCurdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_curd_curd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCurdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurdReq) ProtoMessage() {}

func (x *UpdateCurdReq) ProtoReflect() protoreflect.Message {
	mi := &file_curd_curd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurdReq.ProtoReflect.Descriptor instead.
func (*UpdateCurdReq) Descriptor() ([]byte, []int) {
	return file_curd_curd_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCurdReq) GetCurd() *Curd {
	if x != nil {
		return x.Curd
	}
	return nil
}

type UpdateCurdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Curd *Curd `protobuf:"bytes,1,opt,name=curd,proto3" json:"curd,omitempty"`
}

func (x *UpdateCurdRes) Reset() {
	*x = UpdateCurdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_curd_curd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCurdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurdRes) ProtoMessage() {}

func (x *UpdateCurdRes) ProtoReflect() protoreflect.Message {
	mi := &file_curd_curd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurdRes.ProtoReflect.Descriptor instead.
func (*UpdateCurdRes) Descriptor() ([]byte, []int) {
	return file_curd_curd_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCurdRes) GetCurd() *Curd {
	if x != nil {
		return x.Curd
	}
	return nil
}

type ReadCurdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadCurdReq) Reset() {
	*x = ReadCurdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_curd_curd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCurdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCurdReq) ProtoMessage() {}

func (x *ReadCurdReq) ProtoReflect() protoreflect.Message {
	mi := &file_curd_curd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCurdReq.ProtoReflect.Descriptor instead.
func (*ReadCurdReq) Descriptor() ([]byte, []int) {
	return file_curd_curd_proto_rawDescGZIP(), []int{5}
}

func (x *ReadCurdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadCurdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Curd *Curd `protobuf:"bytes,1,opt,name=curd,proto3" json:"curd,omitempty"`
}

func (x *ReadCurdRes) Reset() {
	*x = ReadCurdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_curd_curd_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCurdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCurdRes) ProtoMessage() {}

func (x *ReadCurdRes) ProtoReflect() protoreflect.Message {
	mi := &file_curd_curd_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCurdRes.ProtoReflect.Descriptor instead.
func (*ReadCurdRes) Descriptor() ([]byte, []int) {
	return file_curd_curd_proto_rawDescGZIP(), []int{6}
}

func (x *ReadCurdRes) GetCurd() *Curd {
	if x != nil {
		return x.Curd
	}
	return nil
}

type DeleteCurdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCurdReq) Reset() {
	*x = DeleteCurdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_curd_curd_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCurdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCurdReq) ProtoMessage() {}

func (x *DeleteCurdReq) ProtoReflect() protoreflect.Message {
	mi := &file_curd_curd_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCurdReq.ProtoReflect.Descriptor instead.
func (*DeleteCurdReq) Descriptor() ([]byte, []int) {
	return file_curd_curd_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCurdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCurdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteCurdRes) Reset() {
	*x = DeleteCurdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_curd_curd_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCurdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCurdRes) ProtoMessage() {}

func (x *DeleteCurdRes) ProtoReflect() protoreflect.Message {
	mi := &file_curd_curd_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCurdRes.ProtoReflect.Descriptor instead.
func (*DeleteCurdRes) Descriptor() ([]byte, []int) {
	return file_curd_curd_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCurdRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListCurdsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCurdsReq) Reset() {
	*x = ListCurdsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_curd_curd_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCurdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurdsReq) ProtoMessage() {}

func (x *ListCurdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_curd_curd_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurdsReq.ProtoReflect.Descriptor instead.
func (*ListCurdsReq) Descriptor() ([]byte, []int) {
	return file_curd_curd_proto_rawDescGZIP(), []int{9}
}

type ListCurdsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Curd *Curd `protobuf:"bytes,1,opt,name=curd,proto3" json:"curd,omitempty"`
}

func (x *ListCurdsRes) Reset() {
	*x = ListCurdsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_curd_curd_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCurdsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurdsRes) ProtoMessage() {}

func (x *ListCurdsRes) ProtoReflect() protoreflect.Message {
	mi := &file_curd_curd_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurdsRes.ProtoReflect.Descriptor instead.
func (*ListCurdsRes) Descriptor() ([]byte, []int) {
	return file_curd_curd_proto_rawDescGZIP(), []int{10}
}

func (x *ListCurdsRes) GetCurd() *Curd {
	if x != nil {
		return x.Curd
	}
	return nil
}

var File_curd_curd_proto protoreflect.FileDescriptor

var file_curd_curd_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x75, 0x72, 0x64, 0x2f, 0x63, 0x75, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x63, 0x75, 0x72, 0x64, 0x22, 0x16, 0x0a, 0x04, 0x43, 0x75, 0x72, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x2f, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x75, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x1e, 0x0a, 0x04, 0x63, 0x75, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x63, 0x75, 0x72, 0x64, 0x2e, 0x43, 0x75, 0x72, 0x64, 0x52, 0x04, 0x63, 0x75, 0x72, 0x64,
	0x22, 0x2f, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x75, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x75, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x63, 0x75, 0x72, 0x64, 0x2e, 0x43, 0x75, 0x72, 0x64, 0x52, 0x04, 0x63, 0x75, 0x72,
	0x64, 0x22, 0x2f, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x75, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x63, 0x75, 0x72, 0x64, 0x2e, 0x43, 0x75, 0x72, 0x64, 0x52, 0x04, 0x63, 0x75,
	0x72, 0x64, 0x22, 0x2f, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x75, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x75, 0x72, 0x64, 0x2e, 0x43, 0x75, 0x72, 0x64, 0x52, 0x04, 0x63,
	0x75, 0x72, 0x64, 0x22, 0x1d, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x43, 0x75, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x2d, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x43, 0x75, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x75, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x63, 0x75, 0x72, 0x64, 0x2e, 0x43, 0x75, 0x72, 0x64, 0x52, 0x04, 0x63, 0x75, 0x72,
	0x64, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x75, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x29, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x75, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x0e, 0x0a,
	0x0c, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x75, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x22, 0x2e, 0x0a,
	0x0c, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x75, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a,
	0x04, 0x63, 0x75, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x75,
	0x72, 0x64, 0x2e, 0x43, 0x75, 0x72, 0x64, 0x52, 0x04, 0x63, 0x75, 0x72, 0x64, 0x32, 0x9e, 0x02,
	0x0a, 0x0b, 0x43, 0x75, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x75, 0x72, 0x64, 0x12, 0x13, 0x2e, 0x63, 0x75,
	0x72, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x75, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x63, 0x75, 0x72, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x75,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x43, 0x75, 0x72,
	0x64, 0x12, 0x11, 0x2e, 0x63, 0x75, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x75, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x63, 0x75, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x43, 0x75, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x75, 0x72, 0x64, 0x12, 0x13, 0x2e, 0x63, 0x75, 0x72, 0x64, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x43, 0x75, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x63, 0x75, 0x72,
	0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x75, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12,
	0x36, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x75, 0x72, 0x64, 0x12, 0x13, 0x2e,
	0x63, 0x75, 0x72, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x75, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x63, 0x75, 0x72, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x75, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x75, 0x72, 0x64, 0x73, 0x12, 0x12, 0x2e, 0x63, 0x75, 0x72, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x75, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x63, 0x75, 0x72, 0x64, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x75, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x30, 0x01, 0x42, 0x14,
	0x5a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x72, 0x2e, 0x67, 0x6f, 0x2f,
	0x63, 0x75, 0x72, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_curd_curd_proto_rawDescOnce sync.Once
	file_curd_curd_proto_rawDescData = file_curd_curd_proto_rawDesc
)

func file_curd_curd_proto_rawDescGZIP() []byte {
	file_curd_curd_proto_rawDescOnce.Do(func() {
		file_curd_curd_proto_rawDescData = protoimpl.X.CompressGZIP(file_curd_curd_proto_rawDescData)
	})
	return file_curd_curd_proto_rawDescData
}

var file_curd_curd_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_curd_curd_proto_goTypes = []interface{}{
	(*Curd)(nil),          // 0: curd.Curd
	(*CreateCurdReq)(nil), // 1: curd.CreateCurdReq
	(*CreateCurdRes)(nil), // 2: curd.CreateCurdRes
	(*UpdateCurdReq)(nil), // 3: curd.UpdateCurdReq
	(*UpdateCurdRes)(nil), // 4: curd.UpdateCurdRes
	(*ReadCurdReq)(nil),   // 5: curd.ReadCurdReq
	(*ReadCurdRes)(nil),   // 6: curd.ReadCurdRes
	(*DeleteCurdReq)(nil), // 7: curd.DeleteCurdReq
	(*DeleteCurdRes)(nil), // 8: curd.DeleteCurdRes
	(*ListCurdsReq)(nil),  // 9: curd.ListCurdsReq
	(*ListCurdsRes)(nil),  // 10: curd.ListCurdsRes
}
var file_curd_curd_proto_depIdxs = []int32{
	0,  // 0: curd.CreateCurdReq.curd:type_name -> curd.Curd
	0,  // 1: curd.CreateCurdRes.curd:type_name -> curd.Curd
	0,  // 2: curd.UpdateCurdReq.curd:type_name -> curd.Curd
	0,  // 3: curd.UpdateCurdRes.curd:type_name -> curd.Curd
	0,  // 4: curd.ReadCurdRes.curd:type_name -> curd.Curd
	0,  // 5: curd.ListCurdsRes.curd:type_name -> curd.Curd
	1,  // 6: curd.CurdService.CreateCurd:input_type -> curd.CreateCurdReq
	5,  // 7: curd.CurdService.ReadCurd:input_type -> curd.ReadCurdReq
	3,  // 8: curd.CurdService.UpdateCurd:input_type -> curd.UpdateCurdReq
	7,  // 9: curd.CurdService.DeleteCurd:input_type -> curd.DeleteCurdReq
	9,  // 10: curd.CurdService.ListCurds:input_type -> curd.ListCurdsReq
	2,  // 11: curd.CurdService.CreateCurd:output_type -> curd.CreateCurdRes
	6,  // 12: curd.CurdService.ReadCurd:output_type -> curd.ReadCurdRes
	4,  // 13: curd.CurdService.UpdateCurd:output_type -> curd.UpdateCurdRes
	8,  // 14: curd.CurdService.DeleteCurd:output_type -> curd.DeleteCurdRes
	10, // 15: curd.CurdService.ListCurds:output_type -> curd.ListCurdsRes
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_curd_curd_proto_init() }
func file_curd_curd_proto_init() {
	if File_curd_curd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_curd_curd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Curd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_curd_curd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCurdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_curd_curd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCurdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_curd_curd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCurdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_curd_curd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCurdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_curd_curd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCurdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_curd_curd_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCurdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_curd_curd_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCurdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_curd_curd_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCurdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_curd_curd_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCurdsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_curd_curd_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCurdsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_curd_curd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_curd_curd_proto_goTypes,
		DependencyIndexes: file_curd_curd_proto_depIdxs,
		MessageInfos:      file_curd_curd_proto_msgTypes,
	}.Build()
	File_curd_curd_proto = out.File
	file_curd_curd_proto_rawDesc = nil
	file_curd_curd_proto_goTypes = nil
	file_curd_curd_proto_depIdxs = nil
}
