apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-postgresql
  labels:
    app: user-postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: user
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: user-postgres-volume
      volumes:
        - name: user-postgres-volume
          persistentVolumeClaim:
            claimName: user-postgres-claim