apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: user
commonLabels:
  app: user
resources:
  - pvc.yaml
  - database-deployment.yaml
  - database-service.yaml
  - deployment.yaml
  - service.yaml