apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: actions-runner
commonLabels:
  app: actions-runner
resources:
  - service-account.yaml
  - role.yaml
  - role-binding.yaml
  - deployment.yaml
