apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: actions-runner
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: localhost:32000/actions-runner
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - kustomize
