apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: actions-runner
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: localhost:32000/actions-runner
    docker:
      dockerfile: Dockerfile
      buildArgs: 
        RUNNER_VERSION: "2.295.0"
        URL: https://github.com/stackhole
        ACTIONS_TOKEN: ABWBMWLY3LEDU7JB2SXVUMDC7XC7Y
deploy:
  kustomize:
    paths:
    - kustomize
