Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.name = 'vagrant-microk8s'
  end
  config.vm.network "forwarded_port", guest: 8888, host: 8888, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8888, host: 8888, protocol: "udp"
  config.vm.network "forwarded_port", guest: 16443, host: 16443, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 16443, host: 16443, protocol: "udp"
  config.vm.network "forwarded_port", guest: 32000, host: 32000, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 32000, host: 32000, protocol: "udp"
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder "./shared", "/home/vagrant/shared"
  config.vm.provision :shell, path: "#{File.dirname(__FILE__)}/setup.sh"
end