apiVersion: apps/v1
kind: Deployment
metadata:
  name: curd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: curd
  template:
    metadata:
      labels:
        app: curd
    spec:
      initContainers:
          - name: curd-migrations
            imagePullPolicy: Always
            image: localhost:32000/curd:latest
            command: ['npm']
            args: ['run','migrate']
      containers:
        - image: localhost:32000/curd:latest
          imagePullPolicy: Always
          name: curd
          env:
            - name: DATABASE_HOST
              value: curd-db.default.svc.cluster.local
            - name: DATABASE_PORT
              value: 5432
            - name: DATABASE_DB
              value: curd
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              value: postgres