apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: oidc-kustomize
resources:
  - pvc.yaml
  - db-deployment.yaml
  - db-service.yaml
  - deployment.yaml
  - service.yaml
  - admin-service.yaml