name: 08 - Deploy User UI
on: workflow_dispatch
jobs:
  deploy-user-ui:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: cd cluster/identity/user-ui
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          cd cluster/identity/user-ui
          npm install
          npm run build
          /home/actions-runner/mc alias set minio http://minio-cli-service.default.svc.cluster.local:9000  ${{ secrets.MINIO_ACCESS_ID }} ${{ secrets.MINIO_ACCESS_SECRET }}
          /home/actions-runner/mc cp --recursive build/* minio/$BUCKET_NAME
        env:
          BUCKET_NAME: user-ui