apiVersion: batch/v1
kind: Job
metadata:
  name: istio-deploy
spec:
  template:
    spec:
      containers:
      - name: istio-deploy
        image: localhost:32000/istio-deploy
        command: ["start.sh"]
        env:
          - name: ISTIO_NAMESPACE
            value: default
          - name: APP_DOMAIN
            value: api
          - name: DOMAIN_ROOT
            value: stackhole.com
          - name: ORGANIZATION
            value: stackhole
          - name: ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: istio-deploy
                key: ACCESS_KEY_ID
          - name: SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: istio-deploy
                key: SECRET_ACCESS_KEY
      restartPolicy: Never
  backoffLimit: 1
