apiVersion: v1
kind: Service
metadata:
  name: minio-cli-service
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - protocol: TCP
      name: api
      port: 9000
      targetPort: 9000
      nodePort: 30900 # make console available via NodePort
    - protocol: TCP
      name: console
      port: 9001
      targetPort: 9001
      nodePort: 30901 # make console available via NodePort