apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: object-storage
commonLabels:
  app: objet-storage
secretGenerator:
  - name: object-storage
    envs:
    - .env.secret
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - cli-service.yaml
  - storage-class.yaml