apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gateway
commonLabels:
  app: gateway
resources:
- http-gateway.yaml
- api-service.yaml
- web-service.yaml
- identity-service.yaml