apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      initContainers:
          - name: user-migrations
            imagePullPolicy: Always
            image: localhost:32000/user:latest
            command: ['npm']
            args: ['run','migrate']
      containers:
        - image: localhost:32000/user:latest
          imagePullPolicy: Always
          name: user
          env:
            - name: DATABASE_HOST
              value: user-db.default.svc.cluster.local
            - name: DATABASE_PORT
              value: 5432
            - name: DATABASE_DB
              value: user
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              value: postgres