name: Deploy Database
on: workflow_dispatch
jobs:
  deploy-database:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd cluster/database
          kubectl apply -k kustomize

