name: 11 - Deploy Erigon
on: workflow_dispatch
jobs:
  deploy-erigon:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd cluster/blockchain/erigon
          kubectl apply -k kustomize
          