name: 03 - Install Istio
on:
  workflow_dispatch:
jobs:
  deploy-istio:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd cluster/03-istio
          bash deploy.sh
