name: 06 - Deploy Minio
on:
  workflow_dispatch:
    inputs:
      bucketName:
        type: string
        default: static
        required: true
      accessKeyId:
        type: string
        default: CHANGE_ME
        required: true
      secretAccessKey:
        type: string
        default: CHANGE_ME
        required: true
jobs:
  deploy-minio:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd cluster/06-object-storage
          bash deploy.sh
        env:
          ACCESS_KEY_ID: ${{ github.event.inputs.accessKeyId }}
          SECRET_ACCESS_KEY: ${{ github.event.inputs.secretAccessKey }}