name: 07 - Deploy Root Web
on:
  workflow_dispatch:
    inputs:
      bucketName:
        type: string
        default: root-web
        required: true
      accessKeyId:
        type: string
        default: CHANGE_ME
        required: true
      secretAccessKey:
        type: string
        default: CHANGE_ME
        required: true
jobs:
  create-web-bucket:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd cluster/07-root-web
          bash deploy.sh
        env:
          BUCKET_NAME: ${{ github.event.inputs.bucketName }}
          ACCESS_KEY_ID: ${{ github.event.inputs.accessKeyId }}
          SECRET_ACCESS_KEY: ${{ github.event.inputs.secretAccessKey }}